### ISSUE TITLE
Facebook single signon doesn't work

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/ToDoLite-Android#16]
Just saw this trying to install on @mschoch's device, and I've seen it before.

I don't have the logs, but it's trivial to reproduce:

* Install facebook app and login
* Install TodoLite from scratch.
* Login

It will give errors in the logs, and no errors in the UI.

**Comment by MossDevlper** [comment]
I notice this is an old bug report, if its still a useful answer. Did you change to your own Facebook app id before trying? Besides that, i had issues on the sync_gateway login, i solved it and put it on the pull request #79.

**Comment by pasin** [comment]
This is not applicable anymore.
