### ISSUE TITLE
Crash reports with email notifications

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/ToDoLite-Android#30]
I think this is important since it might help catch hard-to-reproduce couchbase lite bugs.

Crashlytics seems like the best choice.  @pasin any thoughts on which crash reporting framework you'd recommend?

**Comment by pasin** [comment]
I've never used one for Android apps. [Hockeyapp](http://hockeyapp.net) is the one I used before. Crashlytics looks very promising so I think we could go with Crashlytics.
