### ISSUE TITLE
ToDo Lite 1.0.3  on Play store (and also ToDo Lite iOS) is unable to sync

### ISSUE THREAD

**Issue by tom-cb** [couchbaselabs/ToDoLite-Android#36]
The ToDo application on the Google Play store (and Apple app store) are both no longer able to sync.

I assume something has gone wrong with the back-end sync gateways.

Confirmed on 2 android and 1 iOS device.
This is the version directly from the stores, and has not been compiled locally.

Steps to reproduce:
1. Install ToDo Lite in either Android or iOS.
2. Login
3. Application does not sync

**Comment by tleyden** [comment]
@hideki can you take a look?

**Comment by tleyden** [comment]
+1 I'm seeing the same issue.

**Comment by tleyden** [comment]
This seems more likely to be an issue with the demo cluster rather than todolite, which hasn't changed and used to work.

**Comment by tleyden** [comment]
I *think* the version in the app store corresponds with this tag: https://github.com/couchbaselabs/ToDoLite-Android/tree/1.0.3

**Comment by Jamiltz** [comment]
Log of the requests made after starting the app:

![screen shot 2015-02-23 at 22 00 59](https://cloud.githubusercontent.com/assets/2589337/6338662/5c9be442-bba8-11e4-8d17-fa9819c27e22.png)

**Comment by tleyden** [comment]
@ajres and I are looking into it.  It appears to be a problem with the demo cluster.
