### ISSUE TITLE
Update all time stamps to use UTC for parity with TodoLite iOS

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/ToDoLite-Android#77]
@pasin and I were seeing weird task ordering for the following scenario for TodoLite

```
- Create a list and share
- Add 3 tasks
- Unshare
- Update the First Task with an image
- Have the person who has been unshared with add a task (From Android ForestDB)
- Shows below the other tasks.
```

We found that Todolite-Android was not using the same Datetime as iOS. I have pushed a fix here - https://github.com/couchbaselabs/ToDoLite-Android/commit/e2fae5ad14e3c1ec62f75686427ac9e808b387e5 in branch `feature/use-utc-timezone`

We need to audit all usages of timestamps to make sure they are consistent.

**Comment by pasin** [comment]
Fixed.
