### ISSUE TITLE
Add ability to logout

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/ToDoLite-Android#8]
Same feature request as https://github.com/couchbaselabs/TodoLite-PhoneGap/issues/8

**Comment by Jamiltz** [comment]
https://github.com/Jamiltz/ToDoLite-Android/compare/login_screen
Added a login screen with facebook button to log in/log out

Todos:
- Refactor init of database to be the hash of the user's email straight away. (https://github.com/couchbaselabs/ToDoLite-Android/blob/master/ToDoLite/src/main/java/com/couchbase/todolite/Application.java#L80)
- Add two buttons on login sreen to login via cookie or basic auth (https://github.com/couchbaselabs/ToDoLite-Android/blob/master/ToDoLite/src/main/java/com/couchbase/todolite/Application.java#L62)
