### ISSUE TITLE
Delete tasks when list is deleted

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/ToDoLite-Android#83]
Using TodoLite - 2cb5a0eafa7b43fbdb8bff4471692af2f0112ebb and android 1.3.1-28,

1. person A creates list with tasks
2. person A share list with person B
3. person B looks at list and stays inside list
4. person A deletes list

expected: tasks should delete for person B (TodoLite iOS behavior)
actual: tasks remain

**Comment by pasin** [comment]
It turned out that ToDoLite Android doesn't delete the tasks when a list is deleted.
