### ISSUE TITLE
Dev variant is not mentioned in project

### ISSUE THREAD

**Issue by AlirezaAkbarix** [couchbaselabs/ToDoLite-Android#87]
There is no `Dev` var as you mentioned in the description of project!

**Comment by jamiltz** [comment]
Indeed, after @pasin's major clean up of the source code we forgot to update the readme. I'll update it and remove some sections including that one.

**Comment by AlirezaAkbarix** [comment]
Thanks, So when we are able to use the new readme?

**Comment by jamiltz** [comment]
@AlirezaAkbarix the README has been updated.
