### ISSUE TITLE
Item not pushed from Android -> iOS

### ISSUE THREAD

**Issue by tleyden** [couchbaselabs/ToDoLite-Android#9]
To reproduce:

* Add 4 items from TodoLite ios (from app store)
* On TodoLite Android (master branch), add a photo to one of the items (in this case, The Melt)
* On TodoLite Android, add a new item (in this case, Super Duper) without a photo

Observations:

* The photo of The Melt did not appear on TodoLite ios 
* The Super Duper item did not appear on TodoLite ios

[ios screenshot](http://cl.ly/image/3L0v3O0N2B2W) 
[android screenshot](http://cl.ly/image/3j1k25323X0S)

After doing the above steps, I added a new item on the iOS device "Ayola Gyros", which successfully sync'd to the Android Device.

**Comment by pasin** [comment]
Close as cannot reproduce.
